import Link from "next/link";
import "./globals.css";

import localFont from "next/font/local";
import { getCookie } from "cookies-next";
import { cookies } from "next/headers";

const indieFlower = localFont({
  src: "../../public/fonts/IndieFlower-Regular.ttf",
  variable: "--font-indie-flower",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${indieFlower.variable} font-indieFlower mx-auto max-w-[500px] p-1 `}
      >
        <nav className="border-b border-b-black mb-4">
          <Link href="/">
            <h1 className="font-semibold">[{"don't break the chain"}]</h1>
            {cookies().get("userId")?.value}
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
